version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: increase
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: increase
